title: FlappyPy
description: A Python implementation of the classic Flappy Bird game built with pygame.
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
